dimagi/couchexport

couchexport/writers.py
This resolves [FB 155140](http://manage.dimagi.com/default.asp?155140)
=> Strip HTML from cells when exporting to Excel

couchexport/groupexports.py, couchexport/models.py
1 week timeframe is arbitrary - open to suggestions for change
=> ignore saved exports that haven't been used in a week

couchexport/writers.py
Reverts dimagi/couchexport#112
=> Revert "Strip HTML from cells when exporting to Excel"

couchexport/groupexports.py
=> set last_accessed date during first run

couchexport/templates/couchexport/html_export.html
http://manage.dimagi.com/default.asp?158736
=> add encoding meta to html export template

couchexport/writers.py
http://manage.dimagi.com/default.asp?161695
=> replace 'None' with empty string

couchexport/models.py
=> skip adding extra column is specified

couchexport/models.py, couchexport/tests/test_schema.py
http://manage.dimagi.com/default.asp?163166
=> handle values missing from docs

couchexport/groupexports.py, couchexport/models.py, couchexport/tests/test_saved.py
http://manage.dimagi.com/default.asp?164545
@nickpell /anyone
=> fix the MultipleResultsFound errors when saved exports get in bad states

couchexport/groupexports.py
=> better loging of saved export errors

couchexport/tasks.py
=> ignore unused task results

couchexport/models.py, couchexport/tests/test_schema.py, setup.py
http://manage.dimagi.com/default.asp?167722
@sravfeyn @dannyroberts
=> convert datetime.min to 1970-01-01

couchexport/tasks.py, setup.py
requires: https://github.com/dimagi/django-soil/pull/22
@snopoke 
@gcapalbo
=> expose_cached_downloads

couchexport/tasks.py, setup.py
Reverts dimagi/couchexport#135
=> Revert "expose_cached_downloads"

couchexport/tasks.py, setup.py
Reverts dimagi/couchexport#136
=> Revert "Revert "expose_cached_downloads""

couchexport/groupexports.py, couchexport/tasks.py
This is needed to exclude archived exports from daily saved exports.
@orangejenny
=> Pass filters through and apply them for saved exports

couchexport/tests/test_writers.py
http://manage.dimagi.com/default.asp?169753
@kaapstorm cc @NoahCarnahan
=> simplify test

couchexport/tests/__init__.py, couchexport/tests/test_transforms.py, couchexport/transforms.py
http://manage.dimagi.com/default.asp?171098
@TylerSheffels buddy (i think?).
@dannyroberts fyi
=> fix date transform function and add test

couchexport/tasks.py
depends on https://github.com/dimagi/commcare-hq/pull/7108
=> remove task that is moving to HQ

couchexport/shortcuts.py, couchexport/tasks.py, couchexport/views.py, setup.py
=> mimetype -> content_type

couchexport/models.py, couchexport/views.py
http://manage.dimagi.com/default.asp?179632
@benrudolph 
cc @TylerSheffels 
Tested locally
=> stream export to response

couchexport/writers.py
=> fix link in comment

couchexport/writers.py
=> write numbers in xlsx
